# -*- coding: utf-8 -*-
"""adriana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zx47_EjsPPcq1Yf_zUYzavpo-rqjRcC1
"""

print("bem vindo!")

nome = input("adriana")

num1 = float(input("4.0"))
num2 = float(input("2.0"))

print(f"\nresultados para{nome}")

print(num1 + num2)
print(num1 - num2)
print(num1 * num2)


if num2 != 0:
  print(num1 / num2)
else:
  print("nao é possivel dividir por 0!")